package lt.vu.mybatis.model;

public class Game {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME.ID
     *
     * @mbg.generated Mon Mar 28 21:05:48 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME.COST
     *
     * @mbg.generated Mon Mar 28 21:05:48 EEST 2022
     */
    private Integer cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME.NAME
     *
     * @mbg.generated Mon Mar 28 21:05:48 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME.GENRE_ID
     *
     * @mbg.generated Mon Mar 28 21:05:48 EEST 2022
     */
    private Integer genreId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GAME.ID
     *
     * @return the value of PUBLIC.GAME.ID
     *
     * @mbg.generated Mon Mar 28 21:05:48 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GAME.ID
     *
     * @param id the value for PUBLIC.GAME.ID
     *
     * @mbg.generated Mon Mar 28 21:05:48 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GAME.COST
     *
     * @return the value of PUBLIC.GAME.COST
     *
     * @mbg.generated Mon Mar 28 21:05:48 EEST 2022
     */
    public Integer getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GAME.COST
     *
     * @param cost the value for PUBLIC.GAME.COST
     *
     * @mbg.generated Mon Mar 28 21:05:48 EEST 2022
     */
    public void setCost(Integer cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GAME.NAME
     *
     * @return the value of PUBLIC.GAME.NAME
     *
     * @mbg.generated Mon Mar 28 21:05:48 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GAME.NAME
     *
     * @param name the value for PUBLIC.GAME.NAME
     *
     * @mbg.generated Mon Mar 28 21:05:48 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GAME.GENRE_ID
     *
     * @return the value of PUBLIC.GAME.GENRE_ID
     *
     * @mbg.generated Mon Mar 28 21:05:48 EEST 2022
     */
    public Integer getGenreId() {
        return genreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GAME.GENRE_ID
     *
     * @param genreId the value for PUBLIC.GAME.GENRE_ID
     *
     * @mbg.generated Mon Mar 28 21:05:48 EEST 2022
     */
    public void setGenreId(Integer genreId) {
        this.genreId = genreId;
    }
}